/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IJsonApiTemporary } from "./IJsonApiTemporary";
export * as factories from "./factories";
export { IJsonApiTemporary__factory } from "./factories/IJsonApiTemporary__factory";
